name: TradesRebalance
version: '1.0'
main: dev.oumaimaa.tradesrebalance.TradesRebalance
api-version: '1.21'
author: oumaimaa
description: Replicates Minecraft 23w31a librarian villagers nerf and Wandering Traders offers update
website: https://github.com/4K1D3V/TradesRebalance

commands:
  tradesrebalance:
    description: Main command for TradesRebalance
    usage: /tradesrebalance <reload|info|help>
    aliases: [tr, tradesr]
    permission: tradesrebalance.use

permissions:
  tradesrebalance.use:
    description: Allows use of basic TradesRebalance commands
    default: true
  tradesrebalance.reload:
    description: Allows reloading the plugin configuration
    default: op
  tradesrebalance.admin:
    description: Grants all TradesRebalance permissions
    default: op
    children:
      tradesrebalance.use: true
      tradesrebalance.reload: true